#!/bin/bash
# This script installs updates and informs special services

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    exit 1
fi

# Vars
BASE_DIR="/home/spig/"
TS3_DIR=$BASE_DIR"TS3Server/"

function printNLR() {
ANSI='\033[0;'
RED="${ANSI}31m"
NC="${ANSI}0m"
echo -e "${RED}$1${NC}\n"

}

# Update
printNLR "Fetching updates"
apt -qq update 
printNLR "Available updates"
apt list --upgradable
printNLR "Installing updates\n"
apt-get -yu upgrade

# Notify services
printNLR "Notifying TS33 server..."
eval $BASE_DIR"scripts/ts3-sendmsg.py" 60 10 5 & >> /dev/null
#$USRDIR/scripts/MinecraftScript.sh restart

# Wait
printNLR "Sleeping 60 seconds"
sleep 60

# Restart
printNLR "Shutting down"
eval $TS3_DIR/ts3server_startscript.sh stop &
wait
printNLR "Update complete. Goodnight."
sudo reboot
