#!/bin/bash
# A wrapper for running scripts in ~/scripts/cron 
# and logging to ~/log

# Move to the script directory
cd "$( dirname "${BASH_SOURCE[0]}" )"

# Vars
BASE_DIR=$(dirname `pwd`)
LOG_DIR="$BASE_DIR/log/$1/$(date +%m)/$(date +%d)"
AVAILABLE_SCRIPTS="$BASE_DIR/scripts/cron/"

echo $AVAILABLE_SCRIPTS

# Source environment settings
source "$BASE_DIR/scripts/settings/.allrc"

# Parse args
if [ "$#" -lt 1 ]; then
    echo "Usage: Scriptwrapper [script]"
    echo "Available scripts: "
    for file in $(ls $AVAILABLE_SCRIPTS); do
        echo -e "\t$file"   
    done
    exit 0
fi

SCRIPT=$1
shift

# Setup logging
mkdir -p $LOG_DIR
log="$LOG_DIR/$(date +%H:%M:%S)"

# Validate and execute
files=$(ls $AVAILABLE_SCRIPTS)
for file in $files; do
    if [ "$SCRIPT" == "$file" ]; then
	eval "$AVAILABLE_SCRIPTS/$SCRIPT" $@ &>$log
	exit 0
    fi
done

echo "error: $SCRIPT is not a recognized script"
exit 1
